### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by GsyLocal** [halloweeks/pubg-mobile-unpacker#2]
Hello brother, do you have any contact information, like Telegram or Discord? I'm very interested in unpacking .pak files and would like the opportunity to discuss this. Could you leave your contact information?

**Comment by halloweeks** [comment]
> Hello brother, do you have any contact information, like Telegram or Discord? I'm very interested in unpacking .pak files and would like the opportunity to discuss this. Could you leave your contact information?

https://t.me/halloweeks
